"""Point-mass prefix oracle: distinct request IDs and distinct candidate rows.

Prompt length is three. Target's first output is a=0/b=1. Each subsequent
conditional distribution advances the previous token modulo four. In the
rejection case only the target's second candidate row advances by two.
"""


def position_probabilities(request_id, prefix, *, role, reject_second=False):
    if role not in ("target", "draft") or request_id not in ("a", "b") or len(prefix) < 3:
        raise ValueError("unexpected position fixture input")
    if len(prefix) == 3:
        token = {"a": 0, "b": 1}[request_id]
    else:
        advance = 2 if role == "target" and reject_second and len(prefix) == 5 else 1
        token = (prefix[-1] + advance) % 4
    return [int(i == token) for i in range(4)]


# Explicit expectations, not generated by the tested probability function.
ALL_ACCEPT_OUTPUTS = {"a": [0, 1, 2, 3], "b": [1, 2, 3, 0]}
SECOND_REJECT_OUTPUTS = {"a": [0, 1, 3, 0], "b": [1, 2, 0, 1]}
SECOND_RESIDUAL_ROWS = {"a": ([0, 0, 0, 1], [0, 0, 1, 0]),
                        "b": ([1, 0, 0, 0], [0, 0, 0, 1])}
